# Generated by Django 5.1.5 on 2025-02-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_donations',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
