# Generated by Django 5.1.5 on 2025-02-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_dividends',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='total_donations',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
