# Generated by Django 5.1.5 on 2025-02-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_total_dividends_user_total_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_dividends',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_donations',
            field=models.FloatField(default=0),
        ),
    ]
