# Generated by Django 5.1.5 on 2025-02-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_user_total_donations'),
        ('accounts', '0003_alter_user_total_dividends_and_more'),
    ]

    operations = [
    ]
