# Generated by Django 5.1.5 on 2025-02-17 23:21

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_order',
            name='account',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation_order',
            name='donation_total',
            field=models.FloatField(default=1234.56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation_order',
            name='stripe_transaction_id',
            field=models.TextField(default='123456789'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation_order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
