# Generated by Django 5.1.5 on 2025-04-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('dividend', models.FloatField()),
                ('split', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stock.stockinfo')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'date'], name='stock_stock_stock_i_9724c2_idx')],
            },
        ),
    ]
