# Generated by Django 5.1.5 on 2025-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendreceived',
            name='value',
            field=models.FloatField(editable=False),
        ),
    ]
