# Generated by Django 5.1.5 on 2025-03-03 21:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0002_alter_dividendreceived_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendreceived',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dividendreceived',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
