# Generated by Django 5.1.5 on 2025-03-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_charity_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='charity',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
