# Generated by Django 5.1.5 on 2025-03-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_remove_charity_is_active_alter_charity_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='description',
            field=models.CharField(blank=True, help_text='A brief description about the charity that will be shown on our website.', max_length=300),
        ),
        migrations.AddField(
            model_name='charity',
            name='logo_path',
            field=models.CharField(blank=True, help_text='The path of the logo stored relative to root.', max_length=50),
        ),
    ]
