# Generated by Django 5.1.5 on 2025-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_charity_description_charity_logo_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='email',
            new_name='charity_email',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='name',
            new_name='charity_name',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='phone_number',
            new_name='charity_phone_number',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='description',
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_email',
            field=models.EmailField(default=' ', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_land_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
