# Generated by Django 5.1.5 on 2025-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_charity_description_charity_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='logo_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
