# Generated by Django 5.1.5 on 2025-04-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0005_alter_charity_logo_path'),
        ('charities', '0006_rename_contact_land_name_charity_contact_last_name'),
    ]

    operations = [
    ]
