# Generated by Django 5.1.5 on 2025-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0007_merge_20250402_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='description',
            field=models.CharField(blank=True, help_text='A brief description about the charity that will be shown on our website.', max_length=300),
        ),
    ]
