# Generated by Django 5.1.5 on 2025-03-03 21:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_donation_order_donationorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationorder",
            old_name="time",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="donationorder",
            name="donation_total",
        ),
        migrations.AddField(
            model_name="donationorder",
            name="amount",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="donationorder",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
